### ISSUE TITLE
请问下这个api是最新版吗？

### ISSUE THREAD

**Issue by chucongqing** [tinymins/JX3API#1]
请问下这个api是最新版吗？ 给老婆写个插件发现google不到api文档

**Comment by tinymins** [comment]
这个文档 官方自己都没有你当然谷歌不到 都是插件作者自己整理的 这是新的但是不算最新版 后来没时间继续整理了

**Comment by chucongqing** [comment]
发现剑三对插件开发不太支持啊，自己开发小插件还要认证，弃坑了。 谢谢回复

**Comment by tinymins** [comment]
是不太支持，而且官方程序很不喜欢插件，出了问题都会说是插件导致的，就很烦。之前菊花爆炸了也是被官方的某些人搞的，具体就不多说了省的引战了2333_(:з」∠)_
